### ISSUE TITLE
Load prod.keys and title.keys from app folder

### ISSUE THREAD

**Issue by ghost** [switch-stuff/SwitchExplorer#1]
https://github.com/switch-stuff/SwitchExplorer/blob/665e7c6211d29ae069480002c63616a04b938d9e/Form1.cs#L104

Hello,

Would it be possible please to check if prod.keys and title.keys exist in the app folder before trying to load from %USERPROFILE%/.switch?
A lot of tools use hactool and this one always tries to load title.key from that directory no matter what, and it always fails because of games with a comma, or a strange character, etc. So basically in order to make hactool work for other tools one has to rename/delete the keys on .switch.

But your application uses .switch (I know why, because of the tool to dump the keys), so in order to use your application one has to bring the keys back from the dead, and after use, rename/delete them again not to screw hactool, and so on so forth.
I know I could do a .bat or something like that and run it that way, but just asking if not much trouble for you to introduce a couple ifs in the code and if you're cool with loading from app folder to start with.

**Comment by deurk** [comment]
Agreed, it would be better not to have files in several places for the application.
